server:
  port: 8100

spring:
  data:
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 6379
      password: lkdcode
  datasource:
    url: jdbc:mariadb://localhost:3306/sys
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true